spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            provider: spotify-provider
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: "https://svq-backend.herokuapp.com/api/v1/loggedIn/redirect"
        provider:
          spotify-provider:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: display_name
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:svq
    username: svq-user
    password: ${DATABASE_PASSWORD}
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
springdoc:
  swagger-ui:
    path: /api/v1/swagger
  api-docs:
    path: /api/v1/api-docs
server:
  port: ${PORT}
oauthcontroller:
  params:
    backend-url: https://svq-backend.herokuapp.com
    frontend-dev-url: http://localhost:3000
    frontend-prod-url: https://svq-hipqueue.herokuapp.com
  isDev: ${IS_DEV}